### PR TITLE
Add node-0.12, io.js support for the legacy native code

### PR DESCRIPTION
**Pull request by KenanSulayman**
This adds support for modern versions of node even though the native code is considered obsolete..

And this adds nan and such is now compilable against a variety of engines! :-)

Cheers :kissing_closed_eyes:

### CODE REVIEW

**Comment by Ayms** [comment]
Indeed the initial code is obsolete and therefore pull requests cannot be merged.

**Comment by KenanSulayman** [comment]
Okay, if that's the case: please remove the native code at all. It's of no use and actually prevents this module from installation. *If code shouldn't be used, it shouldn't be shipped.*

**Comment by Ayms** [comment]
Old is a better term than obsolete and as explained it can be used and/or useful.

**Comment by KenanSulayman** [comment]
Then why isn't updating it to an *actually compilable* code base not viable for you? I'm confident that the code is far more useful if people are able to execute the code in order to understand it.

**Pull request closed without merging**
